Controllers/SatController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using DevControl.Models;
using DevControl.Services;
using Microsoft.AspNetCore.Authorization;

namespace DevControl.Controllers;

[Authorize]
public class SatController : Controller
{
    private readonly ILogger<SatController> _logger;
    private readonly IData _data;
    public SatController(ILogger<SatController> logger, IData data)
    {
        _logger = logger;
        _data = data;
    }

    public IActionResult Index()
    {
        _data.AddUsuarioCentro(1010,10);
        return View("list", _data.GetTbUsuarios());
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/TbEstablecimientosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DevControl.Data;
using DevControl.Models.Establecimientos;
using DevControl.Services;
using Microsoft.AspNetCore.Authorization;

namespace DevControl.Controllers
{

    [Authorize]
    public class TbEstablecimientosController : Controller
    {
        private readonly DevContext _context;
        private readonly IData _data;


        public TbEstablecimientosController(DevContext context, IData data)
        {
            _data = data;
            _context = context;
        }

        // GET: TbEstablecimientos
        public IActionResult Index()
        {

            var prov = _context.tbProvincias.ToList();
            var lista = new SelectList(prov, "id", "Provincia");
            ViewData["DbProvincias"] = lista;


            var inst = _context.tbInstitucion.ToList();
            var list_inst = new SelectList(inst, "Id", "Institucion");
            ViewData["DbInstitucion"] = list_inst;

            var cat = _context.tbCategorias.ToList();
            var list_cat = new SelectList(cat, "Id", "Categoria");
            ViewData["DbCategoria"] = list_cat;
            
            return _data.GetVmEstablecimientos() != null ?
                        View(_data.GetVmEstablecimientos()) :
                        Problem("Entity set 'DevContext.tbEstablecimientos'  is null.");
        }

        // GET: TbEstablecimientos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.tbEstablecimientos == null)
            {
                return NotFound();
            }

            var tbEstablecimientos = await _context.tbEstablecimientos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tbEstablecimientos == null)
            {
                return NotFound();
            }

            return View(tbEstablecimientos);
        }

        // GET: TbEstablecimientos/Create
        public IActionResult Create()
        {
            var prov = _context.tbProvincias.ToList();
            var lista = new SelectList(prov, "id", "Provincia");
            ViewData["DbProvincias"] = lista;


            var inst = _context.tbInstitucion.ToList();
            var list_inst = new SelectList(inst, "Id", "Institucion");
            ViewData["DbInstitucion"] = list_inst;

            var subs = _context.tbSubsectors.ToList();
            var list_subs = new SelectList(subs, "Id", "Subsector");
            ViewData["DbSubsectors"] = list_subs;

            var cat = _context.tbCategorias.ToList();
            var list_cat = new SelectList(cat, "Id", "Categoria");
            ViewData["DbCategoria"] = list_cat;

            var nivel = _context.tbNivel.ToList();
            var list_nivel = new SelectList(nivel, "Id", "Nivel");
            ViewData["DbNivel"] = list_nivel;

            var cap = _context.tbCapacidad.Where(x => x.Capacidad != "No procesa").ToList();
            var list_cap = new SelectList(cap, "Id", "Capacidad");
            ViewData["DbCap"] = list_cap;

            List<SelectListItem> YesNo = new List<SelectListItem>();
            YesNo.Add(new SelectListItem { Text = "No", Value = "0" });
            YesNo.Add(new SelectListItem { Text = "Si", Value = "1" });
            ViewData["DbYesNo"] = YesNo;


            return View();
        }

        // POST: TbEstablecimientos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TbEstablecimientos input)
        {
            var idviepi = 0;
            var idsat = "";
            TbEstablecimientos establecimiento = new()
            {
                Centro = input.Centro,
                Institucion = input.Institucion,
                Categoria = input.Categoria,
                Subsector = input.Subsector,
                Nivel = input.Nivel,
                // Capacidad = 0, // input.Capacidad,
                Provincia = input.Provincia,
                Municipio = input.Municipio,
                Distrito = input.Distrito,
                Sector = input.Sector,
                Seccion = input.Seccion,
                Area = input.Area,
                prueba = input.prueba,
                Laboratorio = input.Laboratorio,
                IdViepi = 0, ///input.IdViepi,
                Sat = input.Sat,
                Estado = 1,
                Creacion = DateTime.Now,
                Activacion = DateTime.Now,
                Usuario = input.Usuario
            };


            var cat = _context.tbCategorias.Where(x => x.Id == establecimiento.Categoria).SingleOrDefault();

            // validacion en plataformas
            if (establecimiento.Nivel > 3 || cat.plataforma == 2)
            {
                _data.AddEstablecimiento(establecimiento);
                idviepi = _data.AddEstablecimiento(establecimiento);

            }
            else if (cat.plataforma == 1)
            {
                idsat = _data.AddEstablecimientoSat(establecimiento);

            }
            else
            {
                idviepi = _data.AddEstablecimiento(establecimiento);
                idsat = _data.AddEstablecimientoSat(establecimiento);
                establecimiento.Sat = idsat;
                establecimiento.IdViepi = idviepi;

            }


            if (ModelState.IsValid)
            {
                _context.Add(establecimiento);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(establecimiento);
        }

        // GET: TbEstablecimientos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var tbEstablecimientos = await _context.tbEstablecimientos.FindAsync(id);

            if (id == null || _context.tbEstablecimientos == null)
            {
                return NotFound();
            }
            var prov = _context.tbProvincias.ToList();
            var lista = new SelectList(prov, "id", "Provincia");
            ViewData["DbProvincias"] = lista;


            var inst = _context.tbInstitucion.ToList();
            var list_inst = new SelectList(inst, "Id", "Institucion");
            ViewData["DbInstitucion"] = list_inst;

            var subs = _context.tbSubsectors.ToList();
            var list_subs = new SelectList(subs, "Id", "Subsector");
            ViewData["DbSubsectors"] = list_subs;

            var cat = _context.tbCategorias.ToList();
            var list_cat = new SelectList(cat, "Id", "Categoria");
            ViewData["DbCategoria"] = list_cat;

            var nivel = _context.tbNivel.ToList();
            var list_nivel = new SelectList(nivel, "Id", "Nivel");
            ViewData["DbNivel"] = list_nivel;


            var mun = _context.tbMunicipios.Where(x => Convert.ToInt32(x.provincia) == tbEstablecimientos.Provincia).ToList();
            var list_mun = new SelectList(mun, "Id", "municipio");
            ViewData["DbMun"] = list_mun;

            var municipio = mun.Where(x=>x.Id==tbEstablecimientos.Municipio).SingleOrDefault();
            var dm = _context.tbDistritos.Where(x => (Convert.ToInt32(x.provincia) == tbEstablecimientos.Provincia) && x.municipio == municipio.mun).ToList();
            var list_dm = new SelectList(dm, "Id", "distrito");
            ViewData["DbDm"] = list_dm;

            var se = _context.tbSectores.Where(x => x.Id == tbEstablecimientos.Sector).ToList();
            var list_se = new SelectList(se, "Id", "barrio");
            ViewData["DbSe"] = list_se;

            var sec = _context.tbSecciones.Where(x => x.Id == tbEstablecimientos.Seccion).ToList();
            var list_sec = new SelectList(sec, "Id", "nombreone");
            ViewData["DbSecc"] = list_sec;

            var cap = _context.tbCapacidad.Where(x => x.Capacidad != "No procesa").ToList();
            var list_cap = new SelectList(cap, "Id", "Capacidad");
            ViewData["DbCap"] = list_cap;

            var area = _context.tbArea.Where(x => x.id == tbEstablecimientos.Area || Convert.ToInt32(x.Provincia) == tbEstablecimientos.Provincia).ToList();
            var list_area = new SelectList(area, "id", "Area");
            ViewData["DbArea"] = list_area;

            List<SelectListItem> YesNo = new List<SelectListItem>();
            YesNo.Add(new SelectListItem { Text = "No", Value = "0" });
            YesNo.Add(new SelectListItem { Text = "Si", Value = "1" });
            ViewData["DbYesNo"] = YesNo;

            if (tbEstablecimientos == null)
            {
                return NotFound();
            }
            return View(tbEstablecimientos);
        }

        // POST: TbEstablecimientos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, TbEstablecimientos tbEstablecimientos)
        {
            if (id != tbEstablecimientos.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    if (tbEstablecimientos.IdViepi == null)
                    {
                        tbEstablecimientos.IdViepi = _data.AddEstablecimiento(tbEstablecimientos);
                        _context.Update(tbEstablecimientos);
                        _data.UpEstablecimientoSat(tbEstablecimientos);
                    }
                    else
                    {

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DevControl</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DevControl.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("styles", required: false)

</head>

<body>
    <header>
@if(SignInManager.IsSignedIn(User))
{
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DevControl</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sat" asp-action="Index">SAT</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TbEstablecimientos" asp-action="Index">Establecimientos</a>
                        </li>
                    </ul>
                                        <partial name="_LoginPartial" />

                </div>
            </div>
        </nav>
}
else {
    
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DevControl</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    
                    </ul>
                                        <partial name="_LoginPartial" />
                                                        </div>
            </div>
        </nav>


}
    </header>
    <div class="container">
        <main role="main" class="container">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - cw - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>